### ISSUE TITLE
`ValueError: cannot call `vectorize` on size 0 inputs unless `otypes` is set`  when running `create_sample_sheet` for GSE87571

### ISSUE THREAD

**Issue by ivanajanickova** [Christensen-Lab-Dartmouth/PyMethylProcess#15]
Hello, when following the example for download of GSE87571, I get the following error when running `create_sample_sheet` command.  Could you please help? (I am running the `pyMethylProcess` from a singularity container created form the docker image provided)

`Traceback (most recent call last):
  File "/usr/local/bin/pymethyl-preprocess", line 10, in <module>
    sys.exit(preprocess())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymethylprocess/preprocess.py", line 76, in create_sample_sheet
    pheno_sheet.format_geo(disease_class_column, include_columns)
  File "/usr/local/lib/python3.6/dist-packages/pymethylprocess/PreProcessDataTypes.py", line 138, in format_geo
    idat_basenames = np.unique(np.vectorize(lambda x: '_'.join(x.split('/')[-1].split('_')[:3]))(idats))
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py", line 1972, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py", line 2042, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py", line 1998, in _get_ufunc_and_otypes
    raise ValueError('cannot call `vectorize` on size 0 inputs '
ValueError: cannot call `vectorize` on size 0 inputs unless `otypes` is set`

**Comment by YaoXinZhi** [comment]
Hi, @ivanajanickova. I hope you're doing well! I have try to resolve this error. 

When running the Docker image, I encountered the same problem. I guess it might be related to the code generating samplesheet.csv. 

Using pandas, I extracted the required columns from the original csv, modified the headers line, ensured no duplicates in the Basename column (it's important), and generated samplesheet.csv by myself.

Next, based on the generated samplesheet.csv, following the preprocessing steps in the documentation, I gave it another shot, and guess what? It worked!

Feel free to give it a try. Good luck! :)
