### ISSUE TITLE
qc/norm process reporting errors in my own idat dataset

### ISSUE THREAD

**Issue by YaoXinZhi** [Christensen-Lab-Dartmouth/PyMethylProcess#16]
Hi, I am encountering the following reported error while preprocessing my own methylated idat data using the following command line. Can you please help me to check what is the reason for this error.

Both '-u' and '-qc' work correctly on the example dataset, while only '-qc' works on my dataset and '-u' produces the following error.

errored commend line: 
`pymethyl-preprocess preprocess_pipeline -i ADNI_iDAT_files/ -p minfi -noob -u`

The idat file is from the methylation raw data from ADNI, And i have checked the correctness of the samplesheet.csv file format.

````
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Loading required package: IlluminaHumanMethylationEPICmanifest

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Error in ctrl_g[cc$Address, ] : incorrect number of dimensions

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: In addition:
  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: There were 25 warnings (use warnings() to see them)
  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning:

  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/bin/pymethyl-preprocess", line 10, in <module>
    sys.exit(preprocess())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymethylprocess/preprocess.py", line 282, in preprocess_pipeline
    preprocesser.preprocess_enmix_pipeline(n_cores=n_cores, pipeline=pipeline, noob=noob_norm, use_cache=use_cache, qc_only=qc_only)
  File "/usr/local/lib/python3.6/dist-packages/pymethylprocess/PreProcessDataTypes.py", line 606, in preprocess_enmix_pipeline
    self.preprocessRAW()
  File "/usr/local/lib/python3.6/dist-packages/pymethylprocess/PreProcessDataTypes.py", line 359, in preprocessRAW
    self.qcinfo = self.enmix.QCinfo(self.RGset, detPthre=1e-7)
  File "/usr/local/lib/python3.6/dist-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in ctrl_g[cc$Address, ] : incorrect number of dimensions
````

**Comment by YaoXinZhi** [comment]
OH, I've solved only the problem.

I think because of my carelessness I overlooked the phrase "`Which loads the saved QC/RGSet(s) via the -u option.`" in the documentation.

This meant that I had to generate the RGSet file with `-qc` before I could do the full step with `-u`.

Anyway, thanks for making PyMethyProcess such a handy and effective tool!
